### ISSUE TITLE
tap firing after touchhold unwanted

### ISSUE THREAD

**Issue by johuhype** [jerrybendy/vue-touch-events#56]
Hey, nice work with this plugin!
However I found it unwanted behaviour that the tap event is firing after a touchhold event.

Eg. I am using touchhold to enter multi-select mode and select my first item. After this, the tap is firing and I deselecting it again -> multi-select mode ended.

I would suggest to add the following:

lines 81--
$this.touchHoldTimer = setTimeout(function() {
   triggerEvent(event, $el, 'touchhold');		
   $this.touchHoldFired = true;				
}, $this.options.touchHoldTolerance);

lines 158--
if (!$this.touchHoldFired) {
   triggerEvent(event, this, 'tap');
}

I dont know if anybody needs these two events fired after another, but if so, I would suggest you add an option for it?

Thanks!

**Comment by SreeChandan** [comment]
that's the default behavior. If you hard code this behavior into the plugin then it will prevent any use cases where the default behavior is needed( I have such use cases in my application).
I came into situations like this a lot. And thought about this. 

I think instead of changing how the default events are fired, let's do it in a slightly different way. Let's keep the tap event as it is and introduce a 'tapOnly' event which will only fire when if a tap is all that the user has done. You can extend this pattern to other similar cases. For example, If you listen to a click event and a double click event you usually have to hard code into your app that you don't want the click to happen if the double click happened. Now, as far as I know, this plugin doesn't have a double-tap for double click. But hopefully, my concerns are conveyed.

**Comment by tswonke** [comment]
Is there any workaround for this (tap not being triggered on touchHold)?

**Comment by jerrybendy** [comment]
Ah...Maybe bind `tap` and `touchhold` on different elements?

```html
<div v-touch:tap="tapHandler">
    <span v-touch:touchhold.self="touchHoldHandler">
    <span>
</div>
```

**Comment by jerrybendy** [comment]
This issue is fixed in `v3.0.0`. Now, `touchhold` event doesn't trigger `tap` anymore. If your code depends on this behaivor, maybe you should check and fix it after upgrade to the latest version.

**Comment by tswonke** [comment]
perfect, thanks!!! :-)

**Comment by iamso** [comment]
Hi @jerrybendy, I have just installed `v3.2.3` and the issue is still there. Either it hasn't been fixed or something broke your fix.
When I hold the button, it does trigger the touchhold event, but when I release the button, it also triggers the tap event.
```vue
<div
  v-for="order in orders"
  :key="order.id"
>
  <Button
    v-touch:touchhold="() => onOrderLongpress(order)"
    v-touch:tap="() => onOrderProgress(order)"
  />
</div>
```
